# Generated by Django 3.1.2 on 2020-10-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenitem',
            name='paid_by',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
