# Generated by Django 3.1.2 on 2020-10-01 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_takenitem_paid_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now=True)),
                ('paid_by', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=500)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worker')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
        migrations.DeleteModel(
            name='TakenItem',
        ),
    ]
